services:
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      -  Member-Service-app
  mysql:
    container_name: mysql-Member-Service
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Member-Service
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - Member-Service-app
    restart: unless-stopped

networks:
  Member-Service-app:
    driver: bridge

volumes:
  mysql-data:
