services:
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8060:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - member-service-app

  mysql:
    image: mysql:8.0
    container_name: mysql-member-service
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: membre_db
      MYSQL_USER: membre
      MYSQL_PASSWORD: membrepass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - member-service-app
    restart: unless-stopped

networks:
  member-service-app:
    driver: bridge

volumes:
  mysql-data:
